# Generated by Django 5.0.6 on 2024-05-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'homework', 'verbose_name_plural': 'homework'},
        ),
    ]
